config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "items#index"
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category< ActiveHash::Base

  self.data = [
    { id: 0, name: "---" },
    { id: 1, name: "メンズ" },
    { id: 2, name: "レディース" },
    { id: 3, name: "ベビー・キッズ" },
    { id: 4, name: "インテリア・住まい・小物" },
    { id: 5, name: "本・音楽・ゲーム" },
    { id: 6, name: "おもちゃ・ホビー・グッズ" }
  ]
end

app/models/delivery_days.rb
class DeliveryDays < ActiveHash::Base

  self.data = [
    { id: 0, name: "---" },
    { id: 1, name: "1~2日で発送" },
    { id: 2, name: "2~3日で発送" },
    { id: 3, name: "4~7日で発送" }
  ]
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :status
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :shipping_payer
  belongs_to_active_hash :delivery_days

  has_one_attached :images


  with_options presence: true do
    validates :name
    validates :description
    validates :image
  end

  with_options numericality: { other_than: 0, message: "---以外を選んでください" } do
    validates :category
    validates :status
    validates :shipping_payer
    validates :delivery_days
    validates :prefecture
  end

  validates :price, numericality: { less_than: 9999999, greater_than: 300, message: "300 ~ 9999999の間で価格を入力してください" }

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
    { id: 0, name: "---" },
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/shipping_payer.rb
class ShippingPayer < ActiveHash::Base

  self.data = [
    { id: 0, name: "---" },
    { id: 1, name: "送料込み(出品者負担)" },
    { id: 2, name: "着払い(購入者負担)" }
  ]
end

app/models/status.rb
class Status < ActiveHash::Base

  self.data = [
    { id: 0, name: "---" },
    { id: 1, name: "新品、未使用" },
    { id: 2, name: "未使用に近い" },
    { id: 3, name: "目立った傷や汚れなし" },
    { id: 4, name: "やや傷や汚れがあり" },
    { id: 5, name: "傷や汚れがあり" },
    { id: 6, name: "全体的に状態が悪い" }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_paramaters, if: :devise_controller?

  private

  def configure_permitted_paramaters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.order(created_at: :desc).includes(:user)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @item.update(item_params)
    redirect_to root_path
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image ,:price, :status_id, :delivery_days_id, :prefecture_id, :shipping_payer_id, :description, :category_id).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="container">
  <%= form_with model: item, local: true do |f| %>
    <%= render "shared/error_message", model: f.object %>

    <div class="form-field">
      <%= f.label :image %>
      <%= f.file_field :image, class: "item-image-fileld" %>
    <div>
    <div class="form-field">
      <%= f.label :name %>
      <%= f.text_field :name, class: "item-name-field" %>
    </div>

    <div class="form-field">
      <%= f.label :description %>
      <%= f.text_field :description, class: "item-description-field" %>
    </div>

    <div class="form-field">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name ,class: "item-category-field" %>
    </div>

    <div class="form-field">
      <%= f.label :status_id %>
      <%= f.collection_select :status_id, Status.all, :id, :name ,class: "item-status-field" %>
    </div>

    <div class="form-field">
      <%= f.label :prefecture_id %>
      <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name ,class: "item-prefecture-field" %>
    </div>

    <div class="form-field">
      <%= f.label :delivery_days_id %>
      <%= f.collection_select :delivery_days_id, DeliveryDay.all, :id, :name ,class: "item-status-field" %>
    </div>

    <div class="form-field">
      <%= f.label :shipping_payer_id %>
      <%= f.collection_select :shipping_payer_id, ShippingPayer.all, :id, :name ,class: "item-status-field" %>
    </div>

    <div class="form-field">
      <%= f.label :price %>
      <%= f.text_field :price, class:"item-price-field", placeholder:"例）300" %>
    </div>

    <div class="form-btn">
      <% if controller.controller_name == "items" && controller.action_name == "new" %>
        <%= f.submit "出品する", class: "item-submit" %>
      <% else %>
        <%= f.submit "更新する", class: "item-submit" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= render "form", item: @item %>

app/views/items/index.html.erb
<div class="container">
  <div class="item-container">
    <h2 class="item-theme">新着商品一覧</h2>
    <% if @items.present? %>
      <% @items.each do |item| %>
        <%= link_to item_path do %>
          <div class="item-image">
            <%= image_tag item.image , class: "item-image__src"%>
          </div>
        <% end %>
        <div class="item-container__detail">
          <div class="item-container__name">
            <%= item.name %>
          </div>

          <div class="item-container__price">
            <%= item.price %>円
          </div>
        </div>
      <% end %>
    <% else %>
      <p>まだ商品はありません</p>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<%= render "form", item: @item %>

app/views/items/show.html.erb
<div class="container">
  <div class="item">
    <div class="item__image">
      <%= image_tag @item.image %>
    </div>

    <div class="item__name">
      <div class="item-name">
        <p class="item-name__sentence">
          <%= @item.name %>
        </p>
      </div>
    </div>

    <div class="item__description">
      <div class="item-description">
        <p class="item-description__sentence">
          <%= @item.description %>
        </p>
      </div>
    </div>

    <div class="item-details">
      <table>
        <tbody>
          <tr>
            <td>
              価格
            </td>
            <td>
              <%= @item.price %>円
            </td>
          </tr>
          <tr>
            <td>
              出品者
            </td>
            <td>
              <%= @item.user.nickname %>
            </td>
          </tr>
          <tr>
            <td>
              カテゴリー
            </td>
            <td>
              <%= @item.category.name %>
            </td>
          </tr>
          <tr>
            <td>
              商品の状態
            </td>
            <td>
              <%= @item.status.name %>
            </td>
          </tr>
          <tr>
            <td>
              発送日の目安
            </td>
            <td>
              <%= @item.delivery_days.name %>
            </td>
          </tr>
          <tr>
            <td>
              発送元地域
            </td>
            <td>
              <%= @item.prefecture.name %>
            </td>
          </tr>
          <tr>
            <td>
              配送料負担
            </td>
            <td>
              <%= @item.shipping_payer.name %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ErrorItemApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="user-btns">
      <% if user_signed_in? %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "user-btn" %>
          <%= link_to "出品する", new_item_path , class: "user-btn" %>
        <% if controller.controller_name == "items" && controller.action_name == "show" %>
          <%= link_to "商品削除", item_path(@item) , method: :delete , class: "user-btn" %>
          <%= link_to "商品編集", edit_item_path(@item), class: "user-btn" %>
        <% end %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path , class: "user-btn" %>
        <%= link_to "新規登録", new_user_registration_path , class: "user-btn" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>